<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Results\**" />
    <Compile Remove="Transaction\**" />
    <EmbeddedResource Remove="Results\**" />
    <EmbeddedResource Remove="Transaction\**" />
    <None Remove="Results\**" />
    <None Remove="Transaction\**" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="EasyNetQ" Version="7.8.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
	  <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="6.6.0" />
	  <PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="4.0.0" />
	  <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
	  <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheTechniq.Core\TheTecniQ.Core.csproj" />
    <ProjectReference Include="..\TheTechniq.Data\TheTecniQ.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DynamicPDFs\" />
  </ItemGroup>

</Project>
