using TheTecniQ.Data.Migrations;
using TheTecniQ.Core.Domain.User;
using TheTecniQ.Core.Domain.Permissions;
using TheTecniQ.Core.Domain.Notification;
using TheTecniQ.Core.Domain.Settings;
using TheTecniQ.Core.Domain.Attendance;

namespace TheTecniQ.Data.Migrations
{
    [MigrationInfo("2024-08-12 14:45:00", "Initialize base Schema")]
    public class BaseInitMigration : FluentMigrator.Migration
    {
        public override void Up()
        {

            #region User

            Create
                .Table(nameof(EMS_Role)).WithDescription("Roles")
                .WithColumn(nameof(EMS_Role.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(EMS_Role.Name)).AsAnsiString(100).NotNullable().WithColumnDescription("Role name")
                .WithColumn(nameof(EMS_Role.IsActive)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("For display in further pages")
                .WithColumn(nameof(EMS_Role.IsDeleted)).AsBoolean().NotNullable().WithDefaultValue(0).WithColumnDescription("For delete flag");

            Create
                .Table(nameof(EMS_User)).WithDescription("Users")
                .WithColumn(nameof(EMS_User.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_User.RoleId)).AsInt32().NotNullable().ForeignKey(nameof(EMS_Role), nameof(EMS_Role.Id)).WithColumnDescription("Role Id")
                .WithColumn(nameof(EMS_User.UserName)).AsString(250).NotNullable().WithColumnDescription("Username")
                .WithColumn(nameof(EMS_User.Password)).AsString(250).Nullable().WithColumnDescription("Password")
                .WithColumn(nameof(EMS_User.FirstName)).AsString(250).Nullable().WithColumnDescription("First Name")
                .WithColumn(nameof(EMS_User.LastName)).AsString(250).Nullable().WithColumnDescription("Last Name")
                .WithColumn(nameof(EMS_User.Email)).AsString(250).Nullable().WithColumnDescription("Email")
                .WithColumn(nameof(EMS_User.Mobile)).AsString(250).Nullable().WithColumnDescription("Mobile")
                .WithColumn(nameof(EMS_User.UserToken)).AsString(250).Nullable().WithColumnDescription("Login Token")
                .WithColumn(nameof(EMS_User.IsActive)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("User active or not.")
                .WithColumn(nameof(EMS_User.IsDeleted)).AsBoolean().NotNullable().WithDefaultValue(0).WithColumnDescription("User delete flag")
                .WithColumn(nameof(EMS_User.LastLoggedInOn)).AsDateTime().Nullable().WithColumnDescription("Last Logged-In datetime")
                .WithColumn(nameof(EMS_User.PasswordChangedOn)).AsDateTime().Nullable().WithColumnDescription("Password Changed datetime")
                .WithColumn(nameof(EMS_User.CreatedBy)).AsInt32().Nullable().WithColumnDescription("Created by")
                .WithColumn(nameof(EMS_User.CreatedDate)).AsDateTime().Nullable().WithColumnDescription("Created date time")
                .WithColumn(nameof(EMS_User.ModifyBy)).AsInt32().Nullable().WithColumnDescription("Modify By")
                .WithColumn(nameof(EMS_User.ModifyDate)).AsDateTime().Nullable().WithColumnDescription("Modify Date")
                .WithColumn(nameof(EMS_User.Is2FA)).AsBoolean().NotNullable().WithDefaultValue(false).WithColumnDescription("Is 2 fa active or not")
                .WithColumn(nameof(EMS_User.TwoFaSecretKey)).AsCustom("nvarchar(250)").Nullable().WithColumnDescription("2fa secret key");

            Create
                .Table(nameof(EMS_UserVerificationCode)).WithDescription("User Verification Codes")
                .WithColumn(nameof(EMS_UserVerificationCode.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(EMS_UserVerificationCode.UserId)).AsInt32().NotNullable().ForeignKey(nameof(EMS_User), nameof(EMS_User.Id)).WithColumnDescription("User Id")
                .WithColumn(nameof(EMS_UserVerificationCode.Code)).AsCustom("nvarchar(max)").NotNullable().WithColumnDescription("Code")
                .WithColumn(nameof(EMS_UserVerificationCode.CreateDate)).AsCustom("datetime").NotNullable().WithColumnDescription("Create Date")
                .WithColumn(nameof(EMS_UserVerificationCode.ExpireDate)).AsCustom("datetime").NotNullable().WithColumnDescription("Expire Date")
                .WithColumn(nameof(EMS_UserVerificationCode.IsUse)).AsBoolean().NotNullable().WithColumnDescription("Codes active or not.");

            Create
                .Table(nameof(EMS_UserPasswordHistory)).WithDescription("User Password History")
                .WithColumn(nameof(EMS_UserPasswordHistory.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_UserPasswordHistory.UserId)).AsInt32().ForeignKey(nameof(EMS_User), nameof(EMS_User.Id)).NotNullable().WithColumnDescription("User referance id")
                .WithColumn(nameof(EMS_UserPasswordHistory.Password)).AsAnsiString(250).Nullable().WithColumnDescription("Password")
                .WithColumn(nameof(EMS_UserPasswordHistory.CreatedOn)).AsDateTime().NotNullable().WithColumnDescription("Created date time");
            Create
                .Table(nameof(EMS_tblAttendanceActivation)).WithDescription("EMS_tblAttendanceActivation")
                .WithColumn(nameof(EMS_tblAttendanceActivation.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_tblAttendanceActivation.EmployeeID)).AsInt32().Nullable().WithColumnDescription("Employee Id")
                .WithColumn(nameof(EMS_tblAttendanceActivation.AttendanceDate)).AsDateTime().Nullable().WithColumnDescription("Username")
                .WithColumn(nameof(EMS_tblAttendanceActivation.AttendDays)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("Password")
                .WithColumn(nameof(EMS_tblAttendanceActivation.IsActive)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("User active or not.")
                .WithColumn(nameof(EMS_tblAttendanceActivation.CreatedBy)).AsInt32().Nullable().WithColumnDescription("Created by")
                .WithColumn(nameof(EMS_tblAttendanceActivation.CreatedDate)).AsDateTime().Nullable().WithColumnDescription("Created date time")
                .WithColumn(nameof(EMS_tblAttendanceActivation.ModifyBy)).AsInt32().Nullable().WithColumnDescription("Modify By")
                .WithColumn(nameof(EMS_tblAttendanceActivation.ModifyDate)).AsDateTime().Nullable().WithColumnDescription("Modify Date")
                ;

            Create
                  .Table(nameof(EMS_tblEmployeeExpense)).WithDescription("EMS_tblEmployee Expense")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")                  
                  .WithColumn(nameof(EMS_tblEmployeeExpense.EmployeeID)).AsInt32().Nullable().WithColumnDescription("Employee Id")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.Amount)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("amount")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.ExpenseDate)).AsDateTime().Nullable().WithColumnDescription("Username")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.ExpenseMonth)).AsCustom("nvarchar(max)").Nullable().WithColumnDescription("From email id.")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.Remark)).AsCustom("nvarchar(max)").Nullable().WithColumnDescription("From email id.")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.ExpenseNo)).AsInt32().Nullable().WithColumnDescription("")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.CreatedBy)).AsInt32().Nullable().WithColumnDescription("Created by")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.CreatedDate)).AsDateTime().Nullable().WithColumnDescription("Created date time")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.ModifyBy)).AsInt32().Nullable().WithColumnDescription("Modify By")
                  .WithColumn(nameof(EMS_tblEmployeeExpense.ModifyDate)).AsDateTime().Nullable().WithColumnDescription("Modify Date");

            Create
                .Table(nameof(EMS_tblEmployeeAttendance)).WithDescription("EMS_tblEmployee Expense")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.EmployeeID)).AsInt32().Nullable().WithColumnDescription("Employee Id")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.AttendanceDate)).AsDateTime().Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.AttendDays)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.TotalExpenseAmount)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.TotalAmount)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.SalaryType)).AsCustom("nvarchar(max)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.BasicSalary)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.PayableAmount)).AsCustom("decimal(12,2)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.DivisionName)).AsCustom("nvarchar(500)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.DesignationName)).AsCustom("nvarchar(500)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.DepartmentName)).AsCustom("nvarchar(500)").Nullable().WithColumnDescription("")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.CreatedBy)).AsInt32().Nullable().WithColumnDescription("Created by")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.CreatedDate)).AsDateTime().Nullable().WithColumnDescription("Created date time")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.ModifyBy)).AsInt32().Nullable().WithColumnDescription("Modify By")
                .WithColumn(nameof(EMS_tblEmployeeAttendance.ModifyDate)).AsDateTime().Nullable().WithColumnDescription("Modify Date");

            //if (!Schema.Table(nameof(User)).Column(nameof(User.CreatedBy)).Exists())
            //{
            //    Alter.Table(nameof(User)).AlterColumn(nameof(User.CreatedBy)).AsInt32().NotNullable().ForeignKey(nameof(User), nameof(User.Id)).WithColumnDescription("Created by user id");
            //}
            //if (!Schema.Table(nameof(User)).Column(nameof(User.ModifyBy)).Exists())
            //{
            //    Alter.Table(nameof(User)).AlterColumn(nameof(User.ModifyBy)).AsInt32().Nullable().ForeignKey(nameof(User), nameof(User.Id)).WithColumnDescription("Modify by user id");
            //}

            #endregion










            #region Permission

            Create
                .Table(nameof(EMS_Module)).WithDescription("Modules")
                .WithColumn(nameof(EMS_Module.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_Module.ModuleName)).AsString(250).NotNullable().WithColumnDescription("Module Name")
                .WithColumn(nameof(EMS_Module.IsActive)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("active or not.");

            Create
                .Table(nameof(EMS_Page)).WithDescription("Pages")
                .WithColumn(nameof(EMS_Page.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_Page.ModuleId)).AsInt32().NotNullable().ForeignKey(nameof(EMS_Module), nameof(EMS_Module.Id)).WithColumnDescription("Module Id")
                .WithColumn(nameof(EMS_Page.PageName)).AsString(250).NotNullable().WithColumnDescription("Page Name")
                .WithColumn(nameof(EMS_Page.PageCode)).AsString(250).NotNullable().WithColumnDescription("Page Code")
                .WithColumn(nameof(EMS_Page.IsShowMenu)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Show in menu")
                .WithColumn(nameof(EMS_Page.IsShowSearch)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Show in search in audit table")
                .WithColumn(nameof(EMS_Page.TableNames)).AsCustom("varchar(max)").Nullable().WithColumnDescription("table names with comma separated")
                .WithColumn(nameof(EMS_Page.IsShowView)).AsBoolean().NotNullable().WithDefaultValue(1)
                .WithColumn(nameof(EMS_Page.IsShowAdd)).AsBoolean().NotNullable().WithDefaultValue(1)
                .WithColumn(nameof(EMS_Page.IsShowEdit)).AsBoolean().NotNullable().WithDefaultValue(1)
                .WithColumn(nameof(EMS_Page.IsShowDelete)).AsBoolean().NotNullable().WithDefaultValue(1)
                .WithColumn(nameof(EMS_Page.IsActive)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("active or not.");

            Create
                .Table(nameof(EMS_Permission)).WithDescription("Permissions")
                .WithColumn(nameof(EMS_Permission.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_Permission.RoleId)).AsInt32().NotNullable().ForeignKey(nameof(EMS_Role), nameof(EMS_Role.Id)).WithColumnDescription("Role id")
                .WithColumn(nameof(EMS_Permission.PageId)).AsInt32().NotNullable().ForeignKey(nameof(EMS_Page), nameof(EMS_Page.Id)).WithColumnDescription("Page Id")
                .WithColumn(nameof(EMS_Permission.IsView)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Permission for view")
                .WithColumn(nameof(EMS_Permission.IsAdd)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Permission for add")
                .WithColumn(nameof(EMS_Permission.IsEdit)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Permission for edit")
                .WithColumn(nameof(EMS_Permission.IsDelete)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Permission for delete");

            #endregion

            #region Notification

            Create
                .Table(nameof(EMS_EmailTemplate)).WithDescription("Email Templates")
                .WithColumn(nameof(EMS_EmailTemplate.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_EmailTemplate.FromEmail)).AsString(400).Nullable().WithColumnDescription("From email id.")
                .WithColumn(nameof(EMS_EmailTemplate.FromName)).AsString(100).Nullable().WithColumnDescription("From name.")
                .WithColumn(nameof(EMS_EmailTemplate.TemplateCode)).AsString(200).NotNullable().WithColumnDescription("Template code")
                .WithColumn(nameof(EMS_EmailTemplate.TemplateSubject)).AsString(400).Nullable().WithColumnDescription("Template subject with token.")
                .WithColumn(nameof(EMS_EmailTemplate.TemplateBody)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Template body with token.")
                .WithColumn(nameof(EMS_EmailTemplate.IsActive)).AsBoolean().NotNullable().WithDefaultValue(1).WithColumnDescription("Template active or not.");

            Create
                .Table(nameof(EMS_MailQueue)).WithDescription("Mail Queue")
                .WithColumn(nameof(EMS_MailQueue.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Auto generated unique identifier")
                .WithColumn(nameof(EMS_MailQueue.FromEmail)).AsString(400).NotNullable().WithColumnDescription("From email id.")
                .WithColumn(nameof(EMS_MailQueue.FromName)).AsString(100).Nullable().WithColumnDescription("From name.")
                .WithColumn(nameof(EMS_MailQueue.ToEmail)).AsString(400).NotNullable().WithColumnDescription("To email id.")
                .WithColumn(nameof(EMS_MailQueue.Cc)).AsString().Nullable().WithColumnDescription("CC of emails")
                .WithColumn(nameof(EMS_MailQueue.Bcc)).AsString().Nullable().WithColumnDescription("BCC of emails")
                .WithColumn(nameof(EMS_MailQueue.MailSubject)).AsCustom("varchar(max)").NotNullable().WithColumnDescription("Email subject.")
                .WithColumn(nameof(EMS_MailQueue.MailBody)).AsCustom("varchar(max)").NotNullable().WithColumnDescription("Email body content.")
                .WithColumn(nameof(EMS_MailQueue.AttachmentName)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Attachment Name")
                .WithColumn(nameof(EMS_MailQueue.AttachmentLink)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Attachment Link")
                .WithColumn(nameof(EMS_MailQueue.CreatedDate)).AsDateTime().NotNullable().WithColumnDescription("Record created date.")
                .WithColumn(nameof(EMS_MailQueue.Status)).AsInt16().Nullable().WithColumnDescription("Status of mail.")
                .WithColumn(nameof(EMS_MailQueue.Retry)).AsInt16().Nullable().WithColumnDescription("Sending try count after failure.")
                .WithColumn(nameof(EMS_MailQueue.LastSendingTry)).AsDateTime().Nullable().WithColumnDescription("Last sending try date.")
                .WithColumn(nameof(EMS_MailQueue.LastResponse)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Last try time any message.");

            #endregion

            #region Settings

            Create
                .Table(nameof(EMS_Settings)).WithDescription("Setting cms")
                .WithColumn(nameof(EMS_Settings.Id)).AsInt32().PrimaryKey().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(EMS_Settings.Key)).AsAnsiString(100).NotNullable().WithColumnDescription("Key for setting")
                .WithColumn(nameof(EMS_Settings.Value)).AsAnsiString(250).Nullable().WithColumnDescription("value for setting")
                .WithColumn(nameof(EMS_Settings.IsActive)).AsBoolean().NotNullable().WithDefaultValue(true).WithColumnDescription("value for setting");

            #endregion

            


        }

        public override void Down()
        {
        }
    }
}
